apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netv1-both
  annotations:
    kubernetes.io/ingress.class: both-specific
spec:
  ingressClassName: both-specific
  rules:
    - host: foo-api.dev.arms-dev.net
      http:
        paths:
          - backend:
              service:
                name: foo-api
                port:
                  number: 8080
            path: /networking/v1/both
            pathType: ImplementationSpecific
